databases:
  - name: postgres
    databaseName: recipe-app
    user: alejandro

services:
  - type: web
    name: recipe-app
    env: ruby
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false